apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pvc
  labels:
    type: local
spec:
  storageClassName: awx-local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/grafana/"
